const chapters = {
  cap6: {
    number: 6,
    title: "Alguns Métodos do Cálculo de Variações",
    color: "#4f8ef7",
    colorDim: "rgba(79,142,247,0.12)",
    icon: "∫",
    topics: [
      {
        id: "c6-1",
        title: "Introdução ao Cálculo de Variações",
        difficulty: "easy",
        hours: 2,
        section: "6.1–6.2",
        desc: "Motivação histórica e conexão com a mecânica. O que significa \"extremizar\" um funcional e por que isso é fundamental em física.",
        subtopics: [
          "Problema da braquistócrona",
          "Diferença entre funcional e função",
          "Visão geral do método de Euler",
        ],
        formula: null,
      },
      {
        id: "c6-2",
        title: "Enunciado do Problema Variacional",
        difficulty: "medium",
        hours: 3,
        section: "6.2",
        desc: "Formulação matemática: encontrar y(x) que extremiza J[y] = ∫ f(y, y′, x) dx com condições de contorno fixas.",
        subtopics: [
          "Família de curvas y(x, α)",
          "Variação δy e condições de contorno",
          "Condição necessária de extremo",
        ],
        formula: "J[y] = ∫ f(y, y′, x) dx",
      },
      {
        id: "c6-3",
        title: "Equação de Euler–Lagrange",
        difficulty: "medium",
        hours: 4,
        section: "6.3",
        desc: "Derivação da equação diferencial que toda função extremizante deve satisfazer. Ponto central do capítulo.",
        subtopics: [
          "Derivação via δJ = 0",
          "Lema fundamental do cálculo de variações",
          "Aplicação: geodésicas no plano",
        ],
        formula: "∂f/∂y − d/dx(∂f/∂y′) = 0",
      },
      {
        id: "c6-4",
        title: "Segunda Forma da Equação de Euler",
        difficulty: "medium",
        hours: 3,
        section: "6.4",
        desc: "Forma alternativa útil quando f não depende explicitamente de x.",
        subtopics: [
          "Dedução da forma conservada",
          "Superfície de revolução mínima (catenária)",
          "Braquistócrona resolvida",
        ],
        formula: "f − y′(∂f/∂y′) = const",
      },
      {
        id: "c6-5",
        title: "Várias Variáveis Dependentes",
        difficulty: "medium",
        hours: 2,
        section: "6.5",
        desc: "Generalização para funcionais que dependem de múltiplas funções y₁(x), y₂(x). Cada variável gera sua própria equação de Euler.",
        subtopics: [
          "Sistema de equações de Euler",
          "Exemplo: problema de dois corpos",
        ],
        formula: null,
      },
      {
        id: "c6-6",
        title: "Vínculos e Multiplicadores de Lagrange",
        difficulty: "hard",
        hours: 4,
        section: "6.6",
        desc: "Extremização com condições auxiliares. Uso dos multiplicadores λ(x) para incorporar vínculos diretamente nas equações.",
        subtopics: [
          "Vínculo isoperimétrico",
          "Equações de Euler modificadas",
          "Interpretação física de λ",
          "Corda com comprimento fixo",
        ],
        formula: "δ(J + λK) = 0",
      },
      {
        id: "c6-7",
        title: "A Notação δ (Variação)",
        difficulty: "easy",
        hours: 2,
        section: "6.7",
        desc: "Operador variacional δ como diferencial em espaço de funções. Regras operacionais e relação com d.",
        subtopics: [
          "Linearidade, comutação com ∫ e d/dx",
          "δJ = 0 como princípio de estacionaridade",
          "Preparação para o Princípio de Hamilton",
        ],
        formula: "δ∫f dx = ∫δf dx",
      },
    ],
  },

  cap7: {
    number: 7,
    title: "Princípio de Hamilton — Dinâmica Lagrangiana e Hamiltoniana",
    color: "#a259f7",
    colorDim: "rgba(162,89,247,0.12)",
    icon: "ℒ",
    topics: [
      {
        id: "c7-1",
        title: "Introdução e Contexto",
        difficulty: "easy",
        hours: 1,
        section: "7.1",
        desc: "Por que precisamos de uma nova formulação? Limitações de Newton em sistemas com vínculos e coordenadas não cartesianas.",
        subtopics: [
          "Vínculos holonômicos e não holonômicos",
          "Graus de liberdade",
          "Vantagens da abordagem lagrangiana",
        ],
        formula: null,
      },
      {
        id: "c7-2",
        title: "Princípio de Hamilton",
        difficulty: "medium",
        hours: 3,
        section: "7.2",
        desc: "O movimento real extremiza a ação S = ∫ L dt, onde L = T − V.",
        subtopics: [
          "Definição da ação S",
          "Lagrangiana L = T − V",
          "Equivalência com Newton para sistemas conservativos",
          "Hamilton como postulado fundamental",
        ],
        formula: "δS = δ∫L dt = 0",
      },
      {
        id: "c7-3",
        title: "Coordenadas Generalizadas",
        difficulty: "medium",
        hours: 3,
        section: "7.3",
        desc: "Liberdade de escolher qualquer conjunto de coordenadas qᵢ que descrevam o sistema, respeitando os vínculos.",
        subtopics: [
          "Definição de qᵢ, q̇ᵢ",
          "Transformação para coordenadas generalizadas",
          "Pêndulo simples, duplo, partícula em superfície",
        ],
        formula: "xₐ = xₐ(q₁, q₂, …, qₙ, t)",
      },
      {
        id: "c7-4",
        title: "Equações de Lagrange",
        difficulty: "hard",
        hours: 5,
        section: "7.4",
        desc: "Derivação das equações de movimento a partir do Princípio de Hamilton usando o Cálculo de Variações.",
        subtopics: [
          "Forças generalizadas Qᵢ",
          "Forças não conservativas",
          "Oscilador harmônico via Lagrangiana",
          "Pêndulo esférico",
        ],
        formula: "d/dt(∂L/∂q̇ᵢ) − ∂L/∂qᵢ = 0",
      },
      {
        id: "c7-5",
        title: "Aplicações da Dinâmica Lagrangiana",
        difficulty: "hard",
        hours: 5,
        section: "7.5",
        desc: "Resolução de problemas variados. Ênfase na escolha inteligente de coordenadas generalizadas.",
        subtopics: [
          "Partícula em campo central",
          "Pêndulo com suporte móvel",
          "Partícula sobre cunha deslizante",
          "Sistema de corpos acoplados",
          "Campo eletromagnético",
        ],
        formula: null,
      },
      {
        id: "c7-6",
        title: "Coordenadas Cíclicas e Conservação",
        difficulty: "medium",
        hours: 3,
        section: "7.6",
        desc: "Teoremas de conservação emergem da estrutura da Lagrangiana. Coordenadas cíclicas geram momentos conservados.",
        subtopics: [
          "Momento generalizado pᵢ = ∂L/∂q̇ᵢ",
          "Coordenada cíclica → pᵢ = constante",
          "Simetria de translação → p linear",
          "Simetria rotacional → L angular",
          "Invariância temporal → energia",
        ],
        formula: "pᵢ = ∂L/∂q̇ᵢ = const (cíclica)",
      },
      {
        id: "c7-7",
        title: "Equações Canônicas de Hamilton",
        difficulty: "hard",
        hours: 4,
        section: "7.7–7.8",
        desc: "Transformada de Legendre da Lagrangiana para obter H(qᵢ, pᵢ, t). As equações canônicas substituem as de Lagrange.",
        subtopics: [
          "Transformada de Legendre",
          "H = Σ pᵢq̇ᵢ − L",
          "Espaço de fase (qᵢ, pᵢ)",
          "H como energia total",
        ],
        formula: "q̇ᵢ = ∂H/∂pᵢ,  ṗᵢ = −∂H/∂qᵢ",
      },
      {
        id: "c7-8",
        title: "Teorema de Liouville",
        difficulty: "hard",
        hours: 3,
        section: "7.9",
        desc: "O volume no espaço de fase é preservado pelo fluxo hamiltoniano. Base da mecânica estatística clássica.",
        subtopics: [
          "Fluido de pontos no espaço de fase",
          "Equação de continuidade",
          "dρ/dt = 0",
          "Implicações para termodinâmica",
        ],
        formula: "dρ/dt = ∂ρ/∂t + {ρ, H} = 0",
      },
    ],
  },
};

module.exports = chapters;
